# Generated by Django 5.1.2 on 2024-10-27 00:36

import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'editorial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=70, validators=[libreria.models.validar_titulo])),
                ('paginas', models.PositiveIntegerField()),
                ('fecha_publicacion', models.DateField(null=True)),
                ('imagen', models.URLField(max_length=85, null=True)),
                ('desc_corta', models.CharField(max_length=2000)),
                ('estatus', models.CharField(max_length=1)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('titulo', 'cobol'), _negated=True), name='titulo_no_permitido_chk')],
            },
        ),
    ]
