# Generated by Django 5.1.2 on 2024-10-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editorial',
            table='libreria_editorial',
        ),
    ]
